/*
-----------------------------------------------------------------------------
Filename:    Game_One.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for Kdevelop 4 (March 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __Game_One_h_
#define __Game_One_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
//#include "../res/resource.h"
#endif

#include <CEGUI.h>
#include <CEGUI/RendererModules/Ogre/CEGUIOgreRenderer.h>
#include "OgreResourceGroupManager.h"
#include "OgreResourceManager.h"


class Game_One : public BaseApplication
{
public:
    Game_One(void);
    virtual ~Game_One(void);

protected:
    CEGUI::OgreRenderer *mRenderer;
    
    CEGUI::MouseButton convertButton( OIS::MouseButtonID buttonID );
    
    virtual void createFrameListener(void);
    
    virtual void createScene(void);
    
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);
    
    virtual bool keyPressed( const OIS::KeyEvent &arg ); 
    virtual bool keyReleased( const OIS::KeyEvent &arg );
    
    virtual bool mouseMoved( const OIS::MouseEvent &arg );
    virtual bool mousePressed( const OIS::MouseEvent &arg, OIS::MouseButtonID id );
    
    virtual bool mouseReleased( const OIS::MouseEvent &arg, OIS::MouseButtonID id );
    
    virtual bool quit(const CEGUI::EventArgs &e);
};

#endif // #ifndef __Game_One_h_
